### ISSUE TITLE
Are there any plans to include Envoy contrib versions in func-e?

### ISSUE THREAD

**Issue by ardikabs** [tetratelabs/func-e#450] opened 2024-05-18 04:42 UTC
**Description**
I am curious if func-e will include Envoy contrib versions in the future. Because when I checked https://archive.tetratelabs.io/envoy/envoy-versions.json, I didn't see any contrib versions listed.

**Comment by codefromthecrypt** [comment] 2024-05-18 07:29
dupe of https://github.com/tetratelabs/archive-envoy/issues/37 where the last comment was that it would be similar to how debug images are handled, but someone needs to do the work

**Closed by codefromthecrypt** 2024-05-18 07:29 UTC
Labels: enhancement
