### ISSUE TITLE
Centos 7 support

### ISSUE THREAD

**Issue by adaoud-ims** [tetratelabs/func-e#411] opened 2021-11-16 22:08 UTC
I tried to run func-e on a centos7 but I got an error with GLIBC_2.18 not found.
Is it suppose to work on Centos7 ?

`
[root@9a6cba8c07ab /]# func-e run --config-yaml "admin: {address: {socket_address: {address: '127.0.0.1', port_value: 9901}}}"
looking up the latest Envoy version
downloading https://archive.tetratelabs.io/envoy/download/v1.20.0/envoy-v1.20.0-linux-amd64.tar.xz
starting: /root/.func-e/versions/1.20.0/bin/envoy --config-yaml admin: {address: {socket_address: {address: '127.0.0.1', port_value: 9901}}} --admin-address-path /root/.func-e/runs/1637099786058359687/admin-address.txt
/root/.func-e/versions/1.20.0/bin/envoy: /lib64/libc.so.6: version 'GLIBC_2.18' not found (required by /root/.func-e/versions/1.20.0/bin/envoy)
error: envoy exited with status: 1
`

**Comment by adaoud-ims** [comment] 2021-11-16 22:10
I saw that you manage the rpm package also :
https://cloudsmith.io/~tetrate/repos/getenvoy-rpm-nightly/packages/

Do you still maintaining those package ? Do you have the spec file ?

**Comment by codefromthecrypt** [comment] 2021-11-16 23:56
This is a duplicate of https://github.com/tetratelabs/archive-envoy/issues/17

**Closed by codefromthecrypt** 2021-11-16 23:56 UTC
Labels: enhancement

**Comment by codefromthecrypt** [comment] 2021-11-16 23:59
> I saw that you manage the rpm package also :
https://cloudsmith.io/~tetrate/repos/getenvoy-rpm-nightly/packages/

There is no getenvoy project anymore. While official packages are taking [surprisingly long to become available (>5months)](https://github.com/envoyproxy/envoy/pull/16899), that's the route for system packages of envoy. https://github.com/envoyproxy/envoy/issues/16867#issuecomment-897201483

hope these pointers help!

**Comment by lizan** [comment] 2021-11-17 00:40
Note upstream system package wont support CentOS 7 anyway.
